site_title = "MyArxiv"
limit_days = 7
cache_url = "https://boom-r123.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.CL"
title = "Natural Language Processing"

[[sources]]
limit = 150
category = "cs.MT"
title = "Machine Transaltion"

[[sources]]
limit = 150
category = "cs.NAT"
title = "Non-Autoregressive Translation"

[[sources]]
limit = 150
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"


[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"


[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
